# Generated by Django 5.2.4 on 2025-07-30 11:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(help_text='Название города (например: Берлин)', max_length=100, verbose_name='Город')),
                ('street', models.CharField(help_text='Название улицы (например: Friedrichstraße)', max_length=100, verbose_name='Улица')),
                ('house_number', models.CharField(help_text='Номер здания (например: 12A)', max_length=20, verbose_name='Номер дома')),
                ('postal_code', models.CharField(blank=True, max_length=20, verbose_name='Почтовый индекс')),
                ('country', models.CharField(default='Germany', max_length=100, verbose_name='Страна')),
            ],
            options={
                'verbose_name': 'Локация',
                'verbose_name_plural': 'Локации',
                'constraints': [models.UniqueConstraint(fields=('city', 'street', 'house_number'), name='unique_location_address')],
            },
        ),
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('description', models.TextField(verbose_name='Описание')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена')),
                ('rooms', models.PositiveIntegerField(verbose_name='Количество комнат')),
                ('property_type', models.CharField(choices=[('apartment', 'Студия'), ('loft', 'Лофт'), ('bungalow', 'Бунгало'), ('room', 'Комната')], default='apartment', max_length=20, verbose_name='Тип жилья')),
                ('views_count', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listings', to='users.user')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='listings.location', verbose_name='Местоположение')),
            ],
            options={
                'verbose_name': 'Объявление',
                'verbose_name_plural': 'Объявления',
                'constraints': [models.UniqueConstraint(fields=('title', 'location'), name='unique_listing_title_location')],
            },
        ),
    ]
