# Generated by Django 5.2.4 on 2025-08-06 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='property_type',
            field=models.CharField(choices=[('apartment', 'Студия'), ('loft', 'Лофт'), ('bungalow', 'Бунгало'), ('room', 'Комната'), ('house', 'Дом'), ('commercial', 'Комерческая')], default='apartment', max_length=20, verbose_name='Тип жилья'),
        ),
    ]
