# Generated by Django 5.2.4 on 2025-08-06 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='cancel_deadline',
            field=models.DateField(blank=True, null=True),
        ),
    ]
