# Generated by Django 5.2.4 on 2025-08-11 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0004_remove_booking_is_confirmed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('pending', 'PENDING'), ('confirmed', 'CONFIRMED'), ('cancelled', 'CANCELLED'), ('rejected', 'REJECTED')], default='pending', max_length=20),
        ),
    ]
